/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_DOLPHINDAQ_ROSIE_ROSIE_PB_H_INCLUDED
#define PB_DOLPHINDAQ_ROSIE_ROSIE_PB_H_INCLUDED
#include <pb.h>
#include "timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _dolphindaq_rosie_Metrics {
    pb_callback_t shot_num;
    pb_callback_t shot_time;
    pb_callback_t shot_time_seconds;
    pb_callback_t shot_time_nanos;
    pb_callback_t shot_time_alt_nanos;
} dolphindaq_rosie_Metrics;

typedef struct _dolphindaq_rosie_Data {
    bool has_metrics;
    dolphindaq_rosie_Metrics metrics;
} dolphindaq_rosie_Data;

typedef struct _dolphindaq_rosie_Settings {
    bool has_start_shot_num;
    uint64_t start_shot_num;
    bool has_start_time;
    google_protobuf_Timestamp start_time;
    bool has_metrics_batch_size;
    uint32_t metrics_batch_size;
} dolphindaq_rosie_Settings;


/* Initializer values for message structs */
#define dolphindaq_rosie_Settings_init_default   {false, 0, false, google_protobuf_Timestamp_init_default, false, 0}
#define dolphindaq_rosie_Data_init_default       {false, dolphindaq_rosie_Metrics_init_default}
#define dolphindaq_rosie_Metrics_init_default    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define dolphindaq_rosie_Settings_init_zero      {false, 0, false, google_protobuf_Timestamp_init_zero, false, 0}
#define dolphindaq_rosie_Data_init_zero          {false, dolphindaq_rosie_Metrics_init_zero}
#define dolphindaq_rosie_Metrics_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define dolphindaq_rosie_Metrics_shot_num_tag    1
#define dolphindaq_rosie_Metrics_shot_time_tag   2
#define dolphindaq_rosie_Metrics_shot_time_seconds_tag 3
#define dolphindaq_rosie_Metrics_shot_time_nanos_tag 4
#define dolphindaq_rosie_Metrics_shot_time_alt_nanos_tag 5
#define dolphindaq_rosie_Data_metrics_tag        1
#define dolphindaq_rosie_Settings_start_shot_num_tag 1
#define dolphindaq_rosie_Settings_start_time_tag 2
#define dolphindaq_rosie_Settings_metrics_batch_size_tag 3

/* Struct field encoding specification for nanopb */
#define dolphindaq_rosie_Settings_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   start_shot_num,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  start_time,        2) \
X(a, STATIC,   OPTIONAL, UINT32,   metrics_batch_size,   3)
#define dolphindaq_rosie_Settings_CALLBACK NULL
#define dolphindaq_rosie_Settings_DEFAULT NULL
#define dolphindaq_rosie_Settings_start_time_MSGTYPE google_protobuf_Timestamp

#define dolphindaq_rosie_Data_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metrics,           1)
#define dolphindaq_rosie_Data_CALLBACK NULL
#define dolphindaq_rosie_Data_DEFAULT NULL
#define dolphindaq_rosie_Data_metrics_MSGTYPE dolphindaq_rosie_Metrics

#define dolphindaq_rosie_Metrics_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT64,   shot_num,          1) \
X(a, CALLBACK, REPEATED, MESSAGE,  shot_time,         2) \
X(a, CALLBACK, REPEATED, INT64,    shot_time_seconds,   3) \
X(a, CALLBACK, REPEATED, INT32,    shot_time_nanos,   4) \
X(a, CALLBACK, REPEATED, UINT64,   shot_time_alt_nanos,   5)
#define dolphindaq_rosie_Metrics_CALLBACK pb_default_field_callback
#define dolphindaq_rosie_Metrics_DEFAULT NULL
#define dolphindaq_rosie_Metrics_shot_time_MSGTYPE google_protobuf_Timestamp

extern const pb_msgdesc_t dolphindaq_rosie_Settings_msg;
extern const pb_msgdesc_t dolphindaq_rosie_Data_msg;
extern const pb_msgdesc_t dolphindaq_rosie_Metrics_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define dolphindaq_rosie_Settings_fields &dolphindaq_rosie_Settings_msg
#define dolphindaq_rosie_Data_fields &dolphindaq_rosie_Data_msg
#define dolphindaq_rosie_Metrics_fields &dolphindaq_rosie_Metrics_msg

/* Maximum encoded size of messages (where known) */
#define dolphindaq_rosie_Settings_size           41
/* dolphindaq_rosie_Data_size depends on runtime parameters */
/* dolphindaq_rosie_Metrics_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
