/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_DOLPHINDAQ_TFT_TFT_PB_H_INCLUDED
#define PB_DOLPHINDAQ_TFT_TFT_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _dolphindaq_tft_Image {
    bool has_shot_num;
    uint64_t shot_num;
    bool has_shot_time;
    google_protobuf_Timestamp shot_time;
    bool has_shot_time_alt_nanos;
    uint64_t shot_time_alt_nanos;
    bool has_nx;
    uint32_t nx;
    bool has_ny;
    uint32_t ny;
    pb_callback_t vals;
} dolphindaq_tft_Image;

typedef struct _dolphindaq_tft_ShotAlert {
    bool has_shot_num;
    uint64_t shot_num;
    bool has_shot_time;
    google_protobuf_Timestamp shot_time;
    bool has_shot_time_alt_nanos;
    uint64_t shot_time_alt_nanos;
} dolphindaq_tft_ShotAlert;


/* Initializer values for message structs */
#define dolphindaq_tft_ShotAlert_init_default    {false, 0, false, google_protobuf_Timestamp_init_default, false, 0}
#define dolphindaq_tft_Image_init_default        {false, 0, false, google_protobuf_Timestamp_init_default, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define dolphindaq_tft_ShotAlert_init_zero       {false, 0, false, google_protobuf_Timestamp_init_zero, false, 0}
#define dolphindaq_tft_Image_init_zero           {false, 0, false, google_protobuf_Timestamp_init_zero, false, 0, false, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define dolphindaq_tft_Image_shot_num_tag        1
#define dolphindaq_tft_Image_shot_time_tag       2
#define dolphindaq_tft_Image_shot_time_alt_nanos_tag 3
#define dolphindaq_tft_Image_nx_tag              4
#define dolphindaq_tft_Image_ny_tag              5
#define dolphindaq_tft_Image_vals_tag            6
#define dolphindaq_tft_ShotAlert_shot_num_tag    1
#define dolphindaq_tft_ShotAlert_shot_time_tag   2
#define dolphindaq_tft_ShotAlert_shot_time_alt_nanos_tag 3

/* Struct field encoding specification for nanopb */
#define dolphindaq_tft_ShotAlert_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   shot_num,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  shot_time,         2) \
X(a, STATIC,   OPTIONAL, UINT64,   shot_time_alt_nanos,   3)
#define dolphindaq_tft_ShotAlert_CALLBACK NULL
#define dolphindaq_tft_ShotAlert_DEFAULT NULL
#define dolphindaq_tft_ShotAlert_shot_time_MSGTYPE google_protobuf_Timestamp

#define dolphindaq_tft_Image_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   shot_num,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  shot_time,         2) \
X(a, STATIC,   OPTIONAL, UINT64,   shot_time_alt_nanos,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   nx,                4) \
X(a, STATIC,   OPTIONAL, UINT32,   ny,                5) \
X(a, CALLBACK, OPTIONAL, BYTES,    vals,              6)
#define dolphindaq_tft_Image_CALLBACK pb_default_field_callback
#define dolphindaq_tft_Image_DEFAULT NULL
#define dolphindaq_tft_Image_shot_time_MSGTYPE google_protobuf_Timestamp

extern const pb_msgdesc_t dolphindaq_tft_ShotAlert_msg;
extern const pb_msgdesc_t dolphindaq_tft_Image_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define dolphindaq_tft_ShotAlert_fields &dolphindaq_tft_ShotAlert_msg
#define dolphindaq_tft_Image_fields &dolphindaq_tft_Image_msg

/* Maximum encoded size of messages (where known) */
#define dolphindaq_tft_ShotAlert_size            46
/* dolphindaq_tft_Image_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
