/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "tft.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(dolphindaq_tft_ShotAlert, dolphindaq_tft_ShotAlert, AUTO)


PB_BIND(dolphindaq_tft_Image, dolphindaq_tft_Image, AUTO)



