# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='diode.proto',
  package='dolphindaq.diode',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x64iode.proto\x12\x10\x64olphindaq.diode\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x02\n\x08Settings\x12\x16\n\x0estart_shot_num\x18\x01 \x01(\x04\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0btrace_tvals\x18\x03 \x03(\x01\x12\x10\n\x08trace_dt\x18\x04 \x01(\x01\x12\x10\n\x08trace_nt\x18\x05 \x01(\r\x12\x12\n\ntrace_ymin\x18\x06 \x01(\x01\x12\x12\n\ntrace_ymax\x18\x07 \x01(\x01\x12\x1a\n\x12metrics_batch_size\x18\x08 \x01(\r\x12\n\n\x02\x64t\x18\t \x01(\x01\x12\n\n\x02t1\x18\n \x01(\x01\x12\n\n\x02t2\x18\x0b \x01(\x01\x12\n\n\x02t3\x18\x0c \x01(\x01\x12\n\n\x02t4\x18\r \x01(\x01\x12\x14\n\x0ctimtick_secs\x18\x0e \x01(\x01\x12\x13\n\x0b\x64t_timticks\x18\x0f \x01(\r\x12\x0e\n\x06t1_dts\x18\x10 \x01(\r\x12\x0e\n\x06t2_dts\x18\x11 \x01(\r\x12\x0e\n\x06t3_dts\x18\x12 \x01(\r\x12\x0e\n\x06t4_dts\x18\x13 \x01(\r\"Z\n\x04\x44\x61ta\x12&\n\x05trace\x18\x01 \x01(\x0b\x32\x17.dolphindaq.diode.Trace\x12*\n\x07metrics\x18\x02 \x01(\x0b\x32\x19.dolphindaq.diode.Metrics\"W\n\x05Trace\x12\x10\n\x08shot_num\x18\x01 \x01(\x04\x12-\n\tshot_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05yvals\x18\x03 \x01(\x0c\"\x8e\x03\n\x07Metrics\x12\x10\n\x08shot_num\x18\x01 \x03(\x04\x12-\n\tshot_time\x18\x02 \x03(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x11shot_time_seconds\x18\x03 \x03(\x03\x12\x17\n\x0fshot_time_nanos\x18\x04 \x03(\x05\x12\x1b\n\x13shot_time_alt_nanos\x18\x05 \x03(\x04\x12\x12\n\nglobal_sum\x18\x06 \x03(\x04\x12\x13\n\x0bglobal_mean\x18\x07 \x03(\x01\x12\x12\n\nglobal_max\x18\x08 \x03(\x04\x12\x12\n\nglobal_min\x18\t \x03(\x04\x12\x14\n\x0cglobal_peak5\x18\n \x03(\x04\x12\x0f\n\x07\x62g_mean\x18\x0b \x03(\x01\x12\x13\n\x0bsignal_mean\x18\x0c \x03(\x01\x12\x12\n\nsignal_max\x18\r \x03(\x01\x12\x15\n\rreduced_integ\x18\x0e \x03(\x01\x12\x14\n\x0creduced_mean\x18\x0f \x03(\x01\x12\x13\n\x0breduced_max\x18\x10 \x03(\x01\x12\x0e\n\x06\x63ustom\x18\x11 \x03(\x01')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SETTINGS = _descriptor.Descriptor(
  name='Settings',
  full_name='dolphindaq.diode.Settings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_shot_num', full_name='dolphindaq.diode.Settings.start_shot_num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='dolphindaq.diode.Settings.start_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trace_tvals', full_name='dolphindaq.diode.Settings.trace_tvals', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trace_dt', full_name='dolphindaq.diode.Settings.trace_dt', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trace_nt', full_name='dolphindaq.diode.Settings.trace_nt', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trace_ymin', full_name='dolphindaq.diode.Settings.trace_ymin', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trace_ymax', full_name='dolphindaq.diode.Settings.trace_ymax', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics_batch_size', full_name='dolphindaq.diode.Settings.metrics_batch_size', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dt', full_name='dolphindaq.diode.Settings.dt', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t1', full_name='dolphindaq.diode.Settings.t1', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t2', full_name='dolphindaq.diode.Settings.t2', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t3', full_name='dolphindaq.diode.Settings.t3', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t4', full_name='dolphindaq.diode.Settings.t4', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timtick_secs', full_name='dolphindaq.diode.Settings.timtick_secs', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dt_timticks', full_name='dolphindaq.diode.Settings.dt_timticks', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t1_dts', full_name='dolphindaq.diode.Settings.t1_dts', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t2_dts', full_name='dolphindaq.diode.Settings.t2_dts', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t3_dts', full_name='dolphindaq.diode.Settings.t3_dts', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t4_dts', full_name='dolphindaq.diode.Settings.t4_dts', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=441,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='dolphindaq.diode.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trace', full_name='dolphindaq.diode.Data.trace', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='dolphindaq.diode.Data.metrics', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=533,
)


_TRACE = _descriptor.Descriptor(
  name='Trace',
  full_name='dolphindaq.diode.Trace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shot_num', full_name='dolphindaq.diode.Trace.shot_num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shot_time', full_name='dolphindaq.diode.Trace.shot_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yvals', full_name='dolphindaq.diode.Trace.yvals', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=622,
)


_METRICS = _descriptor.Descriptor(
  name='Metrics',
  full_name='dolphindaq.diode.Metrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shot_num', full_name='dolphindaq.diode.Metrics.shot_num', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shot_time', full_name='dolphindaq.diode.Metrics.shot_time', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shot_time_seconds', full_name='dolphindaq.diode.Metrics.shot_time_seconds', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shot_time_nanos', full_name='dolphindaq.diode.Metrics.shot_time_nanos', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shot_time_alt_nanos', full_name='dolphindaq.diode.Metrics.shot_time_alt_nanos', index=4,
      number=5, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_sum', full_name='dolphindaq.diode.Metrics.global_sum', index=5,
      number=6, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_mean', full_name='dolphindaq.diode.Metrics.global_mean', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_max', full_name='dolphindaq.diode.Metrics.global_max', index=7,
      number=8, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_min', full_name='dolphindaq.diode.Metrics.global_min', index=8,
      number=9, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_peak5', full_name='dolphindaq.diode.Metrics.global_peak5', index=9,
      number=10, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bg_mean', full_name='dolphindaq.diode.Metrics.bg_mean', index=10,
      number=11, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal_mean', full_name='dolphindaq.diode.Metrics.signal_mean', index=11,
      number=12, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal_max', full_name='dolphindaq.diode.Metrics.signal_max', index=12,
      number=13, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reduced_integ', full_name='dolphindaq.diode.Metrics.reduced_integ', index=13,
      number=14, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reduced_mean', full_name='dolphindaq.diode.Metrics.reduced_mean', index=14,
      number=15, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reduced_max', full_name='dolphindaq.diode.Metrics.reduced_max', index=15,
      number=16, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom', full_name='dolphindaq.diode.Metrics.custom', index=16,
      number=17, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=1023,
)

_SETTINGS.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DATA.fields_by_name['trace'].message_type = _TRACE
_DATA.fields_by_name['metrics'].message_type = _METRICS
_TRACE.fields_by_name['shot_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_METRICS.fields_by_name['shot_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Settings'] = _SETTINGS
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Trace'] = _TRACE
DESCRIPTOR.message_types_by_name['Metrics'] = _METRICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Settings = _reflection.GeneratedProtocolMessageType('Settings', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGS,
  __module__ = 'diode_pb2'
  # @@protoc_insertion_point(class_scope:dolphindaq.diode.Settings)
  ))
_sym_db.RegisterMessage(Settings)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'diode_pb2'
  # @@protoc_insertion_point(class_scope:dolphindaq.diode.Data)
  ))
_sym_db.RegisterMessage(Data)

Trace = _reflection.GeneratedProtocolMessageType('Trace', (_message.Message,), dict(
  DESCRIPTOR = _TRACE,
  __module__ = 'diode_pb2'
  # @@protoc_insertion_point(class_scope:dolphindaq.diode.Trace)
  ))
_sym_db.RegisterMessage(Trace)

Metrics = _reflection.GeneratedProtocolMessageType('Metrics', (_message.Message,), dict(
  DESCRIPTOR = _METRICS,
  __module__ = 'diode_pb2'
  # @@protoc_insertion_point(class_scope:dolphindaq.diode.Metrics)
  ))
_sym_db.RegisterMessage(Metrics)


# @@protoc_insertion_point(module_scope)
