# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='dolphindaq',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0bhello.proto\x12\ndolphindaq\"\x9e\x01\n\x05Hello\x12\x13\n\x0bunique_name\x18\x01 \x01(\t\x12\x11\n\tunique_id\x18\x02 \x01(\x03\x12\x31\n\x0b\x64\x65vice_type\x18\x03 \x01(\x0e\x32\x1c.dolphindaq.Hello.DeviceType\":\n\nDeviceType\x12\t\n\x05OTHER\x10\x00\x12\t\n\x05\x44IODE\x10\x01\x12\x0b\n\x07LINECAM\x10\x02\x12\t\n\x05ROSIE\x10\x03')
)



_HELLO_DEVICETYPE = _descriptor.EnumDescriptor(
  name='DeviceType',
  full_name='dolphindaq.Hello.DeviceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIODE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINECAM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROSIE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=128,
  serialized_end=186,
)
_sym_db.RegisterEnumDescriptor(_HELLO_DEVICETYPE)


_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='dolphindaq.Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unique_name', full_name='dolphindaq.Hello.unique_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='dolphindaq.Hello.unique_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='dolphindaq.Hello.device_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HELLO_DEVICETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=186,
)

_HELLO.fields_by_name['device_type'].enum_type = _HELLO_DEVICETYPE
_HELLO_DEVICETYPE.containing_type = _HELLO
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), dict(
  DESCRIPTOR = _HELLO,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:dolphindaq.Hello)
  ))
_sym_db.RegisterMessage(Hello)


# @@protoc_insertion_point(module_scope)
