/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_DOLPHINDAQ_HELLO_PB_H_INCLUDED
#define PB_DOLPHINDAQ_HELLO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _dolphindaq_Hello_DeviceType {
    dolphindaq_Hello_DeviceType_OTHER = 0,
    dolphindaq_Hello_DeviceType_DIODE = 1,
    dolphindaq_Hello_DeviceType_LINECAM = 2,
    dolphindaq_Hello_DeviceType_ROSIE = 3
} dolphindaq_Hello_DeviceType;

/* Struct definitions */
typedef struct _dolphindaq_Hello {
    pb_callback_t unique_name;
    bool has_unique_id;
    int64_t unique_id;
    bool has_device_type;
    dolphindaq_Hello_DeviceType device_type;
} dolphindaq_Hello;


/* Helper constants for enums */
#define _dolphindaq_Hello_DeviceType_MIN dolphindaq_Hello_DeviceType_OTHER
#define _dolphindaq_Hello_DeviceType_MAX dolphindaq_Hello_DeviceType_ROSIE
#define _dolphindaq_Hello_DeviceType_ARRAYSIZE ((dolphindaq_Hello_DeviceType)(dolphindaq_Hello_DeviceType_ROSIE+1))


/* Initializer values for message structs */
#define dolphindaq_Hello_init_default            {{{NULL}, NULL}, false, 0, false, _dolphindaq_Hello_DeviceType_MIN}
#define dolphindaq_Hello_init_zero               {{{NULL}, NULL}, false, 0, false, _dolphindaq_Hello_DeviceType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define dolphindaq_Hello_unique_name_tag         1
#define dolphindaq_Hello_unique_id_tag           2
#define dolphindaq_Hello_device_type_tag         3

/* Struct field encoding specification for nanopb */
#define dolphindaq_Hello_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   unique_name,       1) \
X(a, STATIC,   OPTIONAL, INT64,    unique_id,         2) \
X(a, STATIC,   OPTIONAL, UENUM,    device_type,       3)
#define dolphindaq_Hello_CALLBACK pb_default_field_callback
#define dolphindaq_Hello_DEFAULT NULL

extern const pb_msgdesc_t dolphindaq_Hello_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define dolphindaq_Hello_fields &dolphindaq_Hello_msg

/* Maximum encoded size of messages (where known) */
/* dolphindaq_Hello_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
