/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "rosie.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(dolphindaq_rosie_Settings, dolphindaq_rosie_Settings, AUTO)


PB_BIND(dolphindaq_rosie_Data, dolphindaq_rosie_Data, AUTO)


PB_BIND(dolphindaq_rosie_Metrics, dolphindaq_rosie_Metrics, AUTO)



